# Generated by Django 5.1.4 on 2025-01-28 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('grado_escolar', models.IntegerField()),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id_dimension', models.AutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EscalaValoracion',
            fields=[
                ('id_escala_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('escala_valoracion', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion', models.CharField(max_length=50)),
                ('min_valor', models.IntegerField()),
                ('max_valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GradoEscolar',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('puntos', models.IntegerField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.alumno')),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.evaluacion')),
            ],
        ),
    ]
