# Generated by Django 5.1.4 on 2025-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_escalavaloracion_id_dimension_pregunta_id_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='extra',
            field=models.CharField(default='', max_length=150),
        ),
    ]
