# Generated by Django 5.1.4 on 2025-02-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_resultado_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id_alumno',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='cuestionario.alumno'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id_evaluacion',
            field=models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.CASCADE, to='cuestionario.evaluacion'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
        migrations.AlterModelTable(
            name='dimension',
            table='dimensiones',
        ),
        migrations.AlterModelTable(
            name='evaluacion',
            table='evaluaciones',
        ),
        migrations.AlterModelTable(
            name='resultado',
            table='resultados',
        ),
    ]
